### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Works !

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[hermes.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PAjR4wgJmKt05wPB:-MK4PAjR4wgJmKt05wPC:b-jb15wx) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L2)):*
> ```Python
> #!/bin/python3
> ```

doc string(s) would be good
___
*[hermes.py, line 16 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PmxJ0I6u2gWiVQkO:-MK4PmxJ0I6u2gWiVQkP:bqua3tc) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L16)):*
> ```Python
> 
> def connect_to_slack(token):
>     client = WebClient(token=token)
> ```

what happens if it can't connect? 
___
*[hermes.py, line 23 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4Pvjm9NFarw5GP6Do:-MK4Pvjm9NFarw5GP6Dp:bcaon8w) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L23)):*
> ```Python
>     try:
>         response = client.chat_postMessage(
>             channel='#egg-alerts',
> ```

does it automatically retry if it fails to connect / send?
___
*[hermes.py, line 26 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4POU493YFyVxuKjaZ:-MK4POU493YFyVxuKja_:b-w6wc2g) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L26)):*
> ```Python
>             text=message)
>         assert response["message"]["text"] == message
>     except SlackApiError as e:
> ```

logging might be useful for debugging if messages aren't being sent (i.e expired token). If this is being run as apache there is not stdout to see what the issue is
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4P48ZAoXS-DOI8AyS:-MK4P48ZAoXS-DOI8AyT:bgu2hic) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/README.md#L4)):*
> ```Markdown
> East Genomics private Slack bot !
> 
> This repo uses slackclient to send messages to the egg-alerts channel in binfx.
> ```

readme looks a lil empty

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[hermes.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PAjR4wgJmKt05wPB:-MK4egZ86lmoa1MJpBzH:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

doc string(s) would be good
</blockquote></details>

Done.
___
*[hermes.py, line 16 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PmxJ0I6u2gWiVQkO:-MK4ehE82NA3-Y2d2AFr:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L16)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what happens if it can't connect? 
</blockquote></details>

Done.
___
*[hermes.py, line 23 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4Pvjm9NFarw5GP6Do:-MK4ehoUA5UjkP7eZ3EC:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L23)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does it automatically retry if it fails to connect / send?
</blockquote></details>

Done.
___
*[hermes.py, line 26 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4POU493YFyVxuKjaZ:-MK4eiOg1b6TR5AXUUhF:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

logging might be useful for debugging if messages aren't being sent (i.e expired token). If this is being run as apache there is not stdout to see what the issue is
</blockquote></details>

Done.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4P48ZAoXS-DOI8AyS:-MK4ekU9-caCp2mzLV8D:btupv1y) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

readme looks a lil empty
</blockquote></details>

:man_shrugging:

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[hermes.py, line 16 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PmxJ0I6u2gWiVQkO:-MK4hw1n39cLeYTKyiLG:bmniflj) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L16)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Worth doing retries here too to account for crappy cluster internet, else if it doesn't first time there will be no notification.
Could use https://pypi.org/project/retry/ or similar 
___
*[hermes.py, line 100 at r2](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4h4pv3MeNR0xEJrTd:-MK4h4pv3MeNR0xEJrTe:b-2h2xey) ([raw file](https://github.com/eastgenomics/hermes/blob/c3a2cdf038e884a8d323fcc0bfbf02a02e2b98fc/hermes.py#L100)):*
> ```Python
>             )
>             logger.error(f"Sending message - Retrying...{i} out of 5")
>             i += 1
> ```

would it be better to have a delayed retry? This could be useful https://pypi.org/project/retry/ or similar

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[hermes.py, line 16 at r1](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4PmxJ0I6u2gWiVQkO:-MK4ijYNBUy6eA3Azz2e:bo8qkpq) ([raw file](https://github.com/eastgenomics/hermes/blob/b9e7213ea2e710975e906343be80678b6f21f3fc/hermes.py#L16)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Worth doing retries here too to account for crappy cluster internet, else if it doesn't first time there will be no notification.
Could use https://pypi.org/project/retry/ or similar 
</blockquote></details>

nope it's doesn't care if no internet
Only for sending messages, it cares
___
*[hermes.py, line 100 at r2](https://reviewable.io/reviews/eastgenomics/hermes/1#-MK4h4pv3MeNR0xEJrTd:-MK4mDlc9VgBH6uqPgbw:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/c3a2cdf038e884a8d323fcc0bfbf02a02e2b98fc/hermes.py#L100)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

would it be better to have a delayed retry? This could be useful https://pypi.org/project/retry/ or similar
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
