### PR TITLE
specify token file and channel to send message to

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
Need to update readme with usage. Also add real headers so it looks like an actual used repo instead of someones forgotten about project

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2#-:-MK9TZ6b96Usn20YXkDC:b-7n60vm)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[hermes.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9SrH263AR4sYTXnA2:-MK9SrH263AR4sYTXnA3:b-qd3v92) ([raw file](https://github.com/eastgenomics/hermes/blob/2f6766ba95512d5bf86fededb265b507071e1d46/hermes.py#L8)):*
> ```Python
> 
> Usage:
> python hermes.py msg "Message to send to egg-alerts"
> ```

need to update usage
___
*[hermes.py, line 96 at r1](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9U5Y-2iEhybyx9sxr:-MK9U5Y-2iEhybyx9sxs:b-urpm15) ([raw file](https://github.com/eastgenomics/hermes/blob/2f6766ba95512d5bf86fededb265b507071e1d46/hermes.py#L96)):*
> ```Python
>                 channel=f'#{channel}',
>                 text=message)
>         except Exception as e:
> ```

if this is run in a dx app there will be no logs after the job fails, what gets printed when there's errors?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[hermes.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9SrH263AR4sYTXnA2:-MK9aDhH9MkWlQhmyegW:b-fmfms6) ([raw file](https://github.com/eastgenomics/hermes/blob/2f6766ba95512d5bf86fededb265b507071e1d46/hermes.py#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

need to update usage
</blockquote></details>

would put slack_channel instead of egg-alerts since it could be any channel (i.e. if this is reused for other things in the future)
___
*[hermes.py, line 5 at r2](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9aeAE4k_ULZLFTWeS:-MK9aeAE4k_ULZLFTWeT:b6u2ddx) ([raw file](https://github.com/eastgenomics/hermes/blob/27868314dbe3fa7dce5973ddee6ec6d7a7c105a3/hermes.py#L5)):*
> ```Python
> """ Hermes
> Slack bot to send messages
> Needs Python3.6
> ```

3.6<, also works fine on 3.8
___
*[hermes.py, line 94 at r2](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9bipn7qklfiXVB-U7:-MK9bipn7qklfiXVB-U8:b-ide7un) ([raw file](https://github.com/eastgenomics/hermes/blob/27868314dbe3fa7dce5973ddee6ec6d7a7c105a3/hermes.py#L94)):*
> ```Python
> 
> def connect_to_slack(token, logger, verbose):
>     try:
> ```

doc strings for each function would be better now they are more complex, explain when/why errors are raised 
___
*[README.md, line 11 at r3](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9c1J91wXOFenzx_wV:-MK9c1J91wXOFenzx_wW:bb6iep2) ([raw file](https://github.com/eastgenomics/hermes/blob/5d4613d661ef9d59f464b59ebc17f703bfd3ef33/README.md#L11)):*
> ```Markdown
> ## What is required for this script to run?
> 
> Needs Python3.6 because of slackclient.
> ```

3.6<

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[hermes.py, line 8 at r1](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9SrH263AR4sYTXnA2:-MK9eHYwEtqpRtnoUIZ5:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/2f6766ba95512d5bf86fededb265b507071e1d46/hermes.py#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

would put slack_channel instead of egg-alerts since it could be any channel (i.e. if this is reused for other things in the future)
</blockquote></details>

Done.
___
*[hermes.py, line 5 at r2](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9aeAE4k_ULZLFTWeS:-MK9cPkVCjC0ouuJuHoT:b-qkep35) ([raw file](https://github.com/eastgenomics/hermes/blob/27868314dbe3fa7dce5973ddee6ec6d7a7c105a3/hermes.py#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

3.6<, also works fine on 3.8
</blockquote></details>

it's implieeeeeeeeeeeed
___
*[hermes.py, line 94 at r2](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9bipn7qklfiXVB-U7:-MK9eIJs5bndYhpiuTe7:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/27868314dbe3fa7dce5973ddee6ec6d7a7c105a3/hermes.py#L94)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

doc strings for each function would be better now they are more complex, explain when/why errors are raised 
</blockquote></details>

Done.
___
*[README.md, line 11 at r3](https://reviewable.io/reviews/eastgenomics/hermes/2#-MK9c1J91wXOFenzx_wV:-MK9eKbyCpt5aMF2gWWE:b-896fix) ([raw file](https://github.com/eastgenomics/hermes/blob/5d4613d661ef9d59f464b59ebc17f703bfd3ef33/README.md#L11)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

3.6<
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2#-:-MK9eeHy36HqSOmvG4lb:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/hermes/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
